import './globals.css'
import { rubik } from '../fonts'

export const metadata = {
  title: 'Frontend Mentor - IP address tracker solution',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${rubik.variable}`}>
      <body>{children}</body>
    </html>
  )
}
